In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 

data = pd.read_csv('credit_data.csv') 

In [14]:
print(type(data))
data

<class 'pandas.core.frame.DataFrame'>


id   over_draft  credit_usage                  credit_history  \
0       1           <0             6  critical/other existing credit   
1       2     0<=X<200            48                   existing paid   
2       3  no checking            12  critical/other existing credit   
3       4           <0            42                   existing paid   
4       5           <0            24              delayed previously   
..    ...          ...           ...                             ...   
995   996  no checking            12                   existing paid   
996   997           <0            30                   existing paid   
997   998  no checking            12                   existing paid   
998   999           <0            45                   existing paid   
999  1000     0<=X<200            45  critical/other existing credit   

                 purpose  current_balance Average_Credit_Balance  employment  \
0               radio/tv             1169       no known savings         >=7   
1               radio/tv             5951                   <100      1<=X<4   
2              education             2096                   <100      4<=X<7   
3    furniture/equipment             7882                   <100      4<=X<7   
4                new car             4870                   <100      1<=X<4   
..                   ...              ...                    ...         ...   
995  furniture/equipment             1736                   <100      4<=X<7   
996             used car             3857                   <100      1<=X<4   
997             radio/tv              804                   <100         >=7   
998             radio/tv             1845                   <100      1<=X<4   
999             used car             4576             100<=X<500  unemployed   

     location     personal_status  ... property_magnitude  cc_age  \
0           4         male single  ...        real estate      67   
1           2  female div/dep/mar  ...        real estate      22   
2           2         male single  ...        real estate      49   
3           2         male single  ...     life insurance      45   
4           3         male single  ...  no known property      53   
..        ...                 ...  ...                ...     ...   
995         3  female div/dep/mar  ...        real estate      31   
996         4        male div/sep  ...     life insurance      40   
997         4         male single  ...                car      38   
998         4         male single  ...  no known property      23   
999         3         male single  ...                car      27   

    other_payment_plans   housing existing_credits                        job  \
0                  none       own                2                    skilled   
1                  none       own                1                    skilled   
2                  none       own                1         unskilled resident   
3                  none  for free                1                    skilled   
4                  none  for free                2                    skilled   
..                  ...       ...              ...                        ...   
995                none       own                1         unskilled resident   
996                none       own                1  high qualif/self emp/mgmt   
997                none       own                1                    skilled   
998                none  for free                1                    skilled   
999                none       own                1                    skilled   

     num_dependents own_telephone  foreign_worker class  
0                 1           yes             yes     2  
1                 1          none             yes     1  
2                 2          none             yes     2  
3                 2          none             yes     2  
4                 2          none             yes     1  
..              ...           .

In [33]:
replacements = {
    'good':1,
    'bad':2
}
data['class'].replace(replacements, inplace=True)
data

id   over_draft  credit_usage                  credit_history  \
0       1           <0             6  critical/other existing credit   
1       2     0<=X<200            48                   existing paid   
2       3  no checking            12  critical/other existing credit   
3       4           <0            42                   existing paid   
4       5           <0            24              delayed previously   
..    ...          ...           ...                             ...   
995   996  no checking            12                   existing paid   
996   997           <0            30                   existing paid   
997   998  no checking            12                   existing paid   
998   999           <0            45                   existing paid   
999  1000     0<=X<200            45  critical/other existing credit   

                 purpose  current_balance Average_Credit_Balance  employment  \
0               radio/tv             1169       no known savings         >=7   
1               radio/tv             5951                   <100      1<=X<4   
2              education             2096                   <100      4<=X<7   
3    furniture/equipment             7882                   <100      4<=X<7   
4                new car             4870                   <100      1<=X<4   
..                   ...              ...                    ...         ...   
995  furniture/equipment             1736                   <100      4<=X<7   
996             used car             3857                   <100      1<=X<4   
997             radio/tv              804                   <100         >=7   
998             radio/tv             1845                   <100      1<=X<4   
999             used car             4576             100<=X<500  unemployed   

     location     personal_status  ... property_magnitude  cc_age  \
0           4         male single  ...        real estate      67   
1           2  female div/dep/mar  ...        real estate      22   
2           2         male single  ...        real estate      49   
3           2         male single  ...     life insurance      45   
4           3         male single  ...  no known property      53   
..        ...                 ...  ...                ...     ...   
995         3  female div/dep/mar  ...        real estate      31   
996         4        male div/sep  ...     life insurance      40   
997         4         male single  ...                car      38   
998         4         male single  ...  no known property      23   
999         3         male single  ...                car      27   

    other_payment_plans   housing existing_credits                        job  \
0                  none       own                2                    skilled   
1                  none       own                1                    skilled   
2                  none       own                1         unskilled resident   
3                  none  for free                1                    skilled   
4                  none  for free                2                    skilled   
..                  ...       ...              ...                        ...   
995                none       own                1         unskilled resident   
996                none       own                1  high qualif/self emp/mgmt   
997                none       own                1                    skilled   
998                none  for free                1                    skilled   
999                none       own                1                    skilled   

     num_dependents own_telephone  foreign_worker class  
0                 1           yes             yes     2  
1                 1          none             yes     1  
2                 2          none             yes     2  
3                 2          none             yes     2  
4                 2          none             yes     1  
..              ...           .

In [44]:
new_data = data[['housing','current_balance','location','cc_age','existing_credits','num_dependents','class']]
replacements_x = {
    'own':1,
    'for free':2,
    'rent':3
}
new_data['housing'].replace(replacements_x, inplace=True)
new_data

/home/wingate/.local/lib/python3.6/site-packages/pandas/core/generic.py:6786: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


housing  current_balance  location  cc_age  existing_credits  \
0          1             1169         4      67                 2   
1          1             5951         2      22                 1   
2          1             2096         2      49                 1   
3          2             7882         2      45                 1   
4          2             4870         3      53                 2   
..       ...              ...       ...     ...               ...   
995        1             1736         3      31                 1   
996        1             3857         4      40                 1   
997        1              804         4      38                 1   
998        2             1845         4      23                 1   
999        1             4576         3      27                 1   

     num_dependents  class  
0                 1      2  
1                 1      1  
2                 2      2  
3                 2      2  
4                 2      1  
..              ...    ...  
995               1      2  
996               1      2  
997               1      2  
998               1      1  
999               1      2  

[1000 rows x 7 columns]

In [93]:

x = new_data.iloc[:, range(0,6)].values  
print(x) 
y = new_data.iloc[:, 6].values   
for e in y:
    print(e)


[[   1 1169    4   67    2    1]
 [   1 5951    2   22    1    1]
 [   1 2096    2   49    1    2]
 ...
 [   1  804    4   38    1    1]
 [   2 1845    4   23    1    1]
 [   1 4576    3   27    1    1]]
2
1
2
2
1
2
2
2
2
1
1
1
2
1
2
1
2
2
1
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
1
2
1
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
1
2
1
2
2
1
2
2
1
1
2
2
2
2
1
2
2
2
2
2
1
2
1
2
2
2
1
2
2
2
2
2
2
1
2
1
2
2
1
2
2
1
2
2
2
2
2
2
2
2
2
1
1
2
2
2
2
2
2
1
2
2
1
2
1
2
1
2
2
2
1
2
2
1
2
1
2
1
2
2
2
2
2
1
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
1
2
2
1
1
2
1
2
1
1
2
2
2
2
1
1
1
2
1
2
1
2
1
2
1
1
1
2
1
1
2
1
2
1
2
2
2
1
2
2
2
2
2
2
2
2
1
1
2
2
2
2
2
2
2
2
2
2
2
2
1
1
1
2
1
2
2
2
2
1
1
1
2
2
1
2
1
2
2
2
2
2
2
1
2
2
1
2
2
2
2
1
2
2
2
2
2
2
2
1
2
2
1
2
2
2
2
1
1
2
2
2
1
2
2
2
2
2
2
2
2
2
2
1
2
1
2
2
2
1
2
2
2
2
2
1
1
2
1
2
2
1
1
2
2
2
2
1
2
1
2
2
2
2
1
1
2
2
2
2
2
2
2
2
2
1
1
1
1
1
2
1
2
2
2
2
2
2
2
2
2
2
2
1
2
1
2
1
2
1
2
1
2
1
2
2
2
2
1
2
2
2
1
2
2
2
2
2
1
1
2
2
1
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2


In [103]:
from sklearn.linear_model import LogisticRegression
bnb = LogisticRegression()
y=y.astype('int')

In [104]:
bnb.fit(x,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [113]:
new_data.info()
new_data.to_csv()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
housing             1000 non-null int64
current_balance     1000 non-null int64
location            1000 non-null int64
cc_age              1000 non-null int64
existing_credits    1000 non-null int64
num_dependents      1000 non-null int64
class               1000 non-null int64
dtypes: int64(7)
memory usage: 54.8 KB


',housing,current_balance,location,cc_age,existing_credits,num_dependents,class\n0,1,1169,4,67,2,1,2\n1,1,5951,2,22,1,1,1\n2,1,2096,2,49,1,2,2\n3,2,7882,2,45,1,2,2\n4,2,4870,3,53,2,2,1\n5,2,9055,2,35,1,2,2\n6,1,2835,3,53,1,1,2\n7,3,6948,2,35,1,1,2\n8,1,3059,2,61,1,1,2\n9,1,5234,4,28,2,1,1\n10,3,1295,3,25,1,1,1\n11,3,4308,3,24,1,1,1\n12,1,1567,1,22,1,1,2\n13,1,1199,4,60,2,1,1\n14,3,1403,2,28,1,1,2\n15,1,1282,4,32,1,1,1\n16,1,2424,4,53,2,1,2\n17,1,8072,2,25,3,1,2\n18,2,12579,4,44,1,1,1\n19,1,3430,3,31,1,2,2\n20,1,2134,4,48,3,1,2\n21,3,2647,2,44,1,2,2\n22,3,2241,1,48,2,2,2\n23,1,1804,3,44,1,1,2\n24,1,2069,2,26,2,1,2\n25,1,1374,1,36,1,1,2\n26,1,426,4,39,1,1,2\n27,3,409,3,42,2,1,2\n28,1,2415,3,34,1,1,2\n29,1,6836,3,63,2,1,1\n30,1,1913,3,36,1,1,2\n31,1,4020,2,27,1,1,2\n32,1,5866,2,30,2,1,2\n33,3,1264,4,57,1,1,2\n34,1,1474,4,33,1,1,2\n35,1,4746,4,25,2,1,1\n36,2,6110,1,31,1,1,2\n37,1,2100,4,37,1,1,1\n38,1,1225,2,37,1,1,2\n39,1,458,4,24,1,1,2\n40,1,2333,4,30,1,1,2\n41,1,1158,3,26,1,1,2\n42,1,62

In [106]:
bnb.score(x,y)

0.712

In [107]:
x1test=[[1 ,2050 ,2,49,1,1]]

ynew = bnb.predict(x1test)
for e in ynew:
    print(e)

2


In [112]:
x2test=x
y2new=bnb.predict(x2test)
for e in y2new:
    print(e)

2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
1
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2


In [ ]:
#13